# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainAreaWidgetLayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1271, 323)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_stepper_motors = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_stepper_motors.sizePolicy().hasHeightForWidth())
        self.frame_stepper_motors.setSizePolicy(sizePolicy)
        self.frame_stepper_motors.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_stepper_motors.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_stepper_motors.setObjectName("frame_stepper_motors")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_stepper_motors)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.frame_stepper_motors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_stepper_motor = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_stepper_motor.setFont(font)
        self.label_stepper_motor.setObjectName("label_stepper_motor")
        self.horizontalLayout_3.addWidget(self.label_stepper_motor)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spin_box_port_number = QtWidgets.QSpinBox(self.frame_2)
        self.spin_box_port_number.setObjectName("spin_box_port_number")
        self.horizontalLayout_3.addWidget(self.spin_box_port_number)
        self.btn_select_config = QtWidgets.QPushButton(self.frame_2)
        self.btn_select_config.setEnabled(True)
        self.btn_select_config.setObjectName("btn_select_config")
        self.horizontalLayout_3.addWidget(self.btn_select_config)
        self.btn_add_motor = QtWidgets.QPushButton(self.frame_2)
        self.btn_add_motor.setEnabled(True)
        self.btn_add_motor.setObjectName("btn_add_motor")
        self.horizontalLayout_3.addWidget(self.btn_add_motor)
        self.form_radio_btns = QtWidgets.QFormLayout()
        self.form_radio_btns.setObjectName("form_radio_btns")
        self.radio_btn_config = QtWidgets.QRadioButton(self.frame_2)
        self.radio_btn_config.setObjectName("radio_btn_config")
        self.form_radio_btns.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radio_btn_config)
        self.radio_btn_default = QtWidgets.QRadioButton(self.frame_2)
        self.radio_btn_default.setObjectName("radio_btn_default")
        self.form_radio_btns.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radio_btn_default)
        self.label_config_name = QtWidgets.QLabel(self.frame_2)
        self.label_config_name.setText("")
        self.label_config_name.setObjectName("label_config_name")
        self.form_radio_btns.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_config_name)
        self.horizontalLayout_3.addLayout(self.form_radio_btns)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.frame_stepper_motors, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addWidget(self.frame, 3, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_stepper_motor.setText(_translate("Form", "Stepper Motors"))
        self.label.setText(_translate("Form", "Port:"))
        self.btn_select_config.setText(_translate("Form", "Select Config"))
        self.btn_add_motor.setText(_translate("Form", "Add Motor"))
        self.radio_btn_config.setText(_translate("Form", "add with selected config:"))
        self.radio_btn_default.setText(_translate("Form", "add with default values"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
